### ISSUE TITLE
MYSQL bug

### ISSUE THREAD

**Issue by levitskyyy** [GRX005/Velocity-PlayTime#6]
# Console logs
```
[12:56:17 ERROR]: Couldn't pass DisconnectEvent to velocityplaytime 1.8.5
java.lang.RuntimeException: Error while saving data into the database
        at _1ms.playtime.Handlers.MySQLHandler.saveData(MySQLHandler.java:34) ~[?:?]
        at _1ms.playtime.Main.savePt(Main.java:255) ~[?:?]
        at _1ms.playtime.Listeners.PlaytimeEvents.lambda$onLeave$1(PlaytimeEvents.java:41) ~[?:?]
        at com.velocitypowered.api.event.EventTask$1.execute(EventTask.java:66) ~[velocity.jar:3.3.0-SNAPSHOT (git-2016d148-b436)]
        at com.velocitypowered.proxy.event.VelocityEventManager$ContinuationTask.execute(VelocityEventManager.java:613) ~[velocity.jar:3.3.0-SNAPSHOT (git-2016d148-b436)]
        at com.velocitypowered.proxy.event.VelocityEventManager.fire(VelocityEventManager.java:683) ~[velocity.jar:3.3.0-SNAPSHOT (git-2016d148-b436)]
        at com.velocitypowered.proxy.event.VelocityEventManager.lambda$fire$5(VelocityEventManager.java:541) ~[velocity.jar:3.3.0-SNAPSHOT (git-2016d148-b436)]
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144) ~[?:?]
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642) ~[?:?]
        at java.base/java.lang.Thread.run(Thread.java:1583) [?:?]
Caused by: java.sql.SQLNonTransientConnectionException: (conn=1863927) Connection is closed
        at libs.export.ExceptionFactory.createException(ExceptionFactory.java:300) ~[?:?]
        at libs.export.ExceptionFactory.create(ExceptionFactory.java:378) ~[?:?]
        at libs.Connection.checkNotClosed(Connection.java:700) ~[?:?]
        at libs.Connection.prepareInternal(Connection.java:162) ~[?:?]
        at libs.Connection.prepareStatement(Connection.java:136) ~[?:?]
        at _1ms.playtime.Handlers.MySQLHandler.saveData(MySQLHandler.java:28) ~[?:?]
        ... 9 more
```

**Comment by GRX005** [comment]
Probably it's an issue on your end with the database or something, I didn't see anyone else having the error and neither did I.

**Comment by levitskyyy** [comment]
> Probably it's an issue on your end with the database or something, I didn't see anyone else having the error and neither did I.

Problem only with this plugin. (all plugins are connecting to this db)

**Comment by GRX005** [comment]
🤷‍♂️

**Comment by marcelltorok** [comment]
Any update?

**Comment by GRX005** [comment]
Should be fixed in the latest update.
